
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: khha88838
      POSTGRES_PASSWORD: 55652323
      POSTGRES_DB: myDB
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ~/Documents/Masters/DataManagement/Assignement_02_TPC-H_Data_Loading/TPC_Code/tpch-dbgen:/data
      - ~/Documents/Masters/DataManagement/Postgres_CSV:/csv_data  # NEW VOLUME

    ports:
      - "5432:5432"
    restart: always

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: khha88838@hbku.edu.qa
      PGADMIN_DEFAULT_PASSWORD: 55652323
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: always

volumes:
  postgres_data:
